# Generated by Django 4.2.1 on 2023-12-19 20:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('set_name', models.CharField(max_length=200)),
                ('set_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('nr_of_pieces', models.IntegerField(blank=True, null=True)),
                ('build_status', models.CharField(max_length=50)),
                ('set_location', models.CharField(blank=True, max_length=100, null=True)),
                ('missing_pieces', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None)),
                ('favourited', models.BooleanField()),
            ],
        ),
    ]
