# Generated by Django 4.2.1 on 2023-12-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legocollection',
            options={'ordering': ['collection_id', 'build_status', 'set']},
        ),
        migrations.AlterModelOptions(
            name='legoset',
            options={'ordering': ['set_number']},
        ),
        migrations.AddField(
            model_name='legocollection',
            name='collection_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
