# Generated by Django 4.2.1 on 2023-12-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego_collection', '0002_alter_legocollection_options_alter_legoset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legocollection',
            name='missing_pieces',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
