# Generated by Django 4.2.1 on 2024-01-08 12:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego_collection', '0003_alter_collection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='legoset',
            name='set_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
