# Generated by Django 4.2.1 on 2024-01-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego_collection', '0005_alter_collection_collection_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='lego_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
