# Generated by Django 4.2.1 on 2024-01-08 18:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego_collection', '0006_legoset_lego_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legocollection',
            options={'ordering': ['collection', 'build_status', 'set']},
        ),
        migrations.RenameField(
            model_name='legocollection',
            old_name='col_id',
            new_name='collection',
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_pic',
            field=cloudinary.models.CloudinaryField(default='col-default.png', max_length=255, verbose_name='image'),
        ),
    ]
