# Generated by Django 4.2.1 on 2024-01-09 12:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego_collection', '0007_alter_legocollection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_pic',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
