# Generated by Django 4.2.1 on 2024-01-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego_collection', '0009_alter_collection_collection_pic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legocollection',
            options={'ordering': ['id']},
        ),
    ]
