# Generated by Django 4.2.1 on 2024-02-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego_collection', '0011_alter_legocollection_build_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legocollection',
            name='build_status',
            field=models.CharField(choices=[('NEW', 'New (Owned)'), ('BN', 'Build Next'), ('B', 'Built'), ('STORED', 'Stored'), ('HH', 'Household'), ('WL', 'Wish List')], max_length=50),
        ),
    ]
